before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
    -in service-account.json.enc -out service-account.json -d
language: node_js
node_js:
  - 10
script:
  - npm run prepare
  - npm test
deploy:
  provider: gae
  project: credible-nation-271214
  skip_cleanup: true
